Automatically pass env hash to tools
This commit changes .detect_env such that it no longer exports many
variables, but rather a single associative array. However, Zsh does not
actually allow exporting an associative array to child processes. So we
implement a magic system that allows tools to automagically "pull in"
the associative array of env data if they need it.

diff --git a/zsh/.config/zsh/tools/wstatus b/zsh/.config/zsh/tools/wstatus
--- a/zsh/.config/zsh/tools/wstatus
+++ b/zsh/.config/zsh/tools/wstatus
@@ -3,6 +3,21 @@
 
 # Look up service status for tools such as Slack, Workplace, or Zoom.
 
+# Uses .detect_env if available
+if [[ -z "${DOTFILES_ENV[OPEN_CMD]}" ]]; then
+  if [[ -f "${ZDOTDIR:-$HOME/.config/zsh}/.detect_env" ]]; then
+    source "${ZDOTDIR:-$HOME/.config/zsh}/.detect_env"
+  else
+    >&2 echo ".detect_env not found; falling back to simpler detection"
+    typeset -A DOTFILES_ENV
+    if [[ $(uname) == 'Darwin' ]]; then
+      DOTFILES_ENV[OPEN_CMD]=open
+    else
+      DOTFILES_ENV[OPEN_CMD]=xdg-open
+    fi
+  fi
+fi
+
 typeset -A services
 local services=(
   [blink]=https://status.joinblink.com/
@@ -21,7 +36,7 @@ service=${services[$1]}
 
 if [[ -n $service ]]; then
   printf "Opening \e]8;;${services[$1]}\e\\$1\e]8;;\e\\"
-  $DOTFILES_OPEN_CMD ${services[$1]}
+  ${DOTFILES_ENV[OPEN_CMD]} ${services[$1]}
   echo
 else
   echo 'Unknown service'
